# Default values for oom-event-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# repliaCount -- The number of replicas to run
nameOverride: ""
fullnameOverride: ""
targetSystem: "linux"
namespace: datadog

agents:
  rbac:
    create: true

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

datadog:
  apiKey: <DATADOG_API_KEY>
  apiKeyExistingSecret: # <DATADOG_API_KEY_SECRET>
  appKey: # <DATADOG_APP_KEY>
  appKeySecretName:  # <DATADOG_APP_KEY_SECRET>
  clusterChecks:
    enabled: false
  orchestratorExplorer:
    enabled: false
  securityAgent:
    compliance:
      enabled: false
  logLevel: INFO

clusterAgent:
  replicas: 1
  image:
    repository: datadog/agent
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 7.23.0
  command:
  - trace-agent
  - -config=/etc/datadog-agent/datadog.yaml
  enabled: true
  token: # <DATADOG_CLUSTER_AGENT_TOKEN>
  metricsProvider:
    enabled: true
    port: 8126
    service:
      type: ClusterIP
      port: 8126
    aggregator: avg
    wpaController: false
    useDatadogMetrics: false
  priorityClassName: fairwinds-critical
  rbac:
    create: true
    serviceAccountName: datadog
  admissionController:
    enabled: false
  healthPort: 5555
  livenessProbe:
    failureThreshold: 6
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    tcpSocket:
      port: 8126
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 6
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    tcpSocket:
      port: 8126
    timeoutSeconds: 5
  resources:
    limits:
      cpu: 250m
      memory: 350Mi
    requests:
      cpu: 250m
      memory: 350Mi


nodeSelector: {}

tolerations: []

affinity: {}
